wandb_version: 1

_name_or_path:
  desc: null
  value: google/t5-xl-lm-adapt
accelerator_config:
  desc: null
  value:
    dispatch_batches: null
    even_batches: true
    gradient_accumulation_kwargs: null
    non_blocking: false
    split_batches: false
    use_seedable_sampler: true
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - T5ForConditionalGeneration
auto_find_batch_size:
  desc: null
  value: false
bad_words_ids:
  desc: null
  value: null
batch_eval_metrics:
  desc: null
  value: false
begin_suppress_tokens:
  desc: null
  value: null
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
bos_token_id:
  desc: null
  value: null
cache_dir:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
classifier_dropout:
  desc: null
  value: 0.0
cross_attention_hidden_size:
  desc: null
  value: null
d_ff:
  desc: null
  value: 5120
d_kv:
  desc: null
  value: 64
d_model:
  desc: null
  value: 2048
data_seed:
  desc: null
  value: null
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_persistent_workers:
  desc: null
  value: false
dataloader_pin_memory:
  desc: null
  value: true
dataloader_prefetch_factor:
  desc: null
  value: null
ddp_backend:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_timeout:
  desc: null
  value: 1800
debug:
  desc: null
  value: []
decoder_start_token_id:
  desc: null
  value: 0
deepspeed:
  desc: null
  value: null
dense_act_fn:
  desc: null
  value: gelu_new
disable_tqdm:
  desc: null
  value: false
dispatch_batches:
  desc: null
  value: null
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: false
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: false
dropout_rate:
  desc: null
  value: 0.1
early_stopping:
  desc: null
  value: false
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
eval_do_concat_batches:
  desc: null
  value: true
eval_on_start:
  desc: null
  value: false
eval_steps:
  desc: null
  value: null
eval_strategy:
  desc: null
  value: 'no'
evaluation_strategy:
  desc: null
  value: null
exponential_decay_length_penalty:
  desc: null
  value: null
feed_forward_proj:
  desc: null
  value: gated-gelu
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fsdp:
  desc: null
  value: []
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
    xla_fsdp_v2: false
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
full_determinism:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 8
gradient_checkpointing:
  desc: null
  value: false
gradient_checkpointing_kwargs:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
hub_always_push:
  desc: null
  value: false
hub_model_id:
  desc: null
  value: null
hub_private_repo:
  desc: null
  value: false
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
ignore_data_skip:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
include_num_input_tokens_seen:
  desc: null
  value: false
include_tokens_per_second:
  desc: null
  value: false
initializer_factor:
  desc: null
  value: 1.0
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: true
is_gated_act:
  desc: null
  value: true
jit_mode_eval:
  desc: null
  value: false
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
label_names:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
layer_norm_epsilon:
  desc: null
  value: 1.0e-06
learning_rate:
  desc: null
  value: 2.0e-05
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: /mnt/bn/data-tns-live-llm/leon/datasets/p3_exp1/runs/Jul01_16-09-47_n193-016-158
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 100
logging_strategy:
  desc: null
  value: steps
lr_scheduler_kwargs:
  desc: null
  value: {}
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: null
min_length:
  desc: null
  value: 0
model/num_parameters:
  desc: null
  value: 2854475776
model_max_length:
  desc: null
  value: 1024
model_type:
  desc: null
  value: t5
mp_parameters:
  desc: null
  value: ''
neftune_noise_alpha:
  desc: null
  value: null
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_decoder_layers:
  desc: null
  value: 24
num_heads:
  desc: null
  value: 32
num_layers:
  desc: null
  value: 24
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 2.0
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: null
optim_target_modules:
  desc: null
  value: null
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: /mnt/bn/data-tns-live-llm/leon/datasets/p3_exp1
output_hidden_states:
  desc: null
  value: false
output_past:
  desc: null
  value: true
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
peft_config:
  desc: null
  value:
    default: 'LoraConfig(peft_type=<PeftType.LORA: ''LORA''>, auto_mapping=None, base_model_name_or_path=''google/t5-xl-lm-adapt'',
      revision=None, task_type=<TaskType.SEQ_2_SEQ_LM: ''SEQ_2_SEQ_LM''>, inference_mode=False,
      r=8, target_modules={''q'', ''v''}, lora_alpha=16, lora_dropout=0.1, fan_in_fan_out=False,
      bias=''none'', use_rslora=False, modules_to_save=None, init_lora_weights=True,
      layers_to_transform=None, layers_pattern=None, rank_pattern={}, alpha_pattern={},
      megatron_config=None, megatron_core=''megatron.core'', loftq_config={}, use_dora=False,
      layer_replication=None)'
per_device_eval_batch_size:
  desc: null
  value: 8
per_device_train_batch_size:
  desc: null
  value: 32
per_gpu_eval_batch_size:
  desc: null
  value: null
per_gpu_train_batch_size:
  desc: null
  value: null
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
quantization_config:
  desc: null
  value:
    _load_in_4bit: true
    _load_in_8bit: false
    bnb_4bit_compute_dtype: bfloat16
    bnb_4bit_quant_storage: uint8
    bnb_4bit_quant_type: nf4
    bnb_4bit_use_double_quant: false
    llm_int8_enable_fp32_cpu_offload: false
    llm_int8_has_fp16_weight: false
    llm_int8_skip_modules: null
    llm_int8_threshold: 6.0
    load_in_4bit: true
    load_in_8bit: false
    quant_method: QuantizationMethod.BITS_AND_BYTES
ray_scope:
  desc: null
  value: last
relative_attention_max_distance:
  desc: null
  value: 128
relative_attention_num_buckets:
  desc: null
  value: 32
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value:
  - wandb
restore_callback_states_from_checkpoint:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: /mnt/bn/data-tns-live-llm/leon/datasets/p3_exp1
save_on_each_node:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
save_safetensors:
  desc: null
  value: true
save_steps:
  desc: null
  value: 100
save_strategy:
  desc: null
  value: steps
save_total_limit:
  desc: null
  value: 3
seed:
  desc: null
  value: 42
sep_token_id:
  desc: null
  value: null
skip_memory_metrics:
  desc: null
  value: true
split_batches:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tf32:
  desc: null
  value: null
tf_legacy_loss:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: false
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
torch_dtype:
  desc: null
  value: float32
torchdynamo:
  desc: null
  value: null
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
transformers_version:
  desc: null
  value: 4.42.1
typical_p:
  desc: null
  value: 1.0
use_bfloat16:
  desc: null
  value: false
use_cache:
  desc: null
  value: true
use_cpu:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
use_legacy_prediction_loop:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 32128
warmup_ratio:
  desc: null
  value: 0.03
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
