wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.72
    framework: huggingface
    huggingface_version: 4.42.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    start_time: 1719814240.718812
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.9.2
      5: 0.13.72
      6: 4.42.1
      8:
      - 5
